### ISSUE TITLE
如何写一个项目的readme

### ISSUE THREAD

**Issue by fridego** [guozhi666/Student-selection-system#2]
每一个项目都是自己的作品， 既然花费了时间和精力去构建， 额外花点时间（相比代码部分）完善它的文档是非常值得的；
1. 文档需要直观地告诉别人这是个什么项目， 以及你希望通过项目传递什么样的价值。
比如你现在要做一个新闻发布系统， 目的是为了在创作过程中学习各种知识和技能， 那么这个文档就可以包含至少两个部分， 第一个部分是有关项目的设计， 实现思路， 数据表设计， 最终实现的效果等。 第二部分是把你在这个过程中学到的东西形成分小文档， 可以类似这种： 如何在github上创建和管理新项目， 如何使用markdown管理项目文档， 如何解决项目提交冲突， 等等，当然还有第三， 第四等，  所有在项目中遇到的问题， 都可以总结归纳一下。

**Comment by guozhi666** [comment]
好的，我今天会注意写一下的

**Comment by fridego** [comment]
gitbook 的使用方式
1. 确保安装gitbook 可以通过cmd命令行运行gitbook 命令， 如果出现使用提示， 说明已经安装成功
2. 创建一个gitbook文档 gitbook init guoz（文件夹名字）， 然后会自动创建一个项目
3. 进入到文件夹， 输入gitbook serve命令， 这个项目就运行起来了， 默认是4000端口， 然后在浏览器输入localhost:4000, 就可以预览这个文档了

**Comment by guozhi666** [comment]
好的
