### ISSUE TITLE
保护个人隐私

### ISSUE THREAD

**Issue by fridego** [guozhi666/Student-selection-system#3]
出于保护隐私的考虑， 项目里的课程报告部分可以删除， 里面包含的个人信息太多了（通过本地删除， 然后推到远程， 或者把这个项目删除， 重新创建并删除--删除后应该可以回退找到的，重新创建项目比较稳妥）

**Comment by guozhi666** [comment]
好的，我把报告直接取出来，不过你昨天演示的操作步骤我有点不熟悉，所以我还需要百度一下再熟悉一下
