### ISSUE TITLE
有关新闻发布系统的进度

### ISSUE THREAD

**Issue by fridego** [guozhi666/Student-selection-system#5]
1. 先把页面和结构搭建起来，主要页面有： 
登录页面  
前端：  1主页（按照分类展示新闻），2分类页面， 3 新闻详情页面
后端：  4增加文章页面（一个大的表单）， 5添加分类页面（分类自主创建），6新闻列表页面（包含 文章标题， 时间， 类别， 作者， 以及删除， 编辑， 预览操作按钮--- 编辑可以调出添加新闻页面， 预览调新闻详情页面）， 这一部分可以在草稿上画一下， 争取三天结束
2 数据库设计 
用户表， 文章表， 新闻分类表  一天时间结束
3 前后端数据联调， 权限控制， 搜索， 安全等 3-4天
加油吧

**Comment by guozhi666** [comment]
ok,我自己再按进度修改

**Comment by fridego** [comment]
嗯， 很好！
有问题及时反馈。
